name: Build

on:
  push:

jobs:
  build-android:
    name: Build android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: fewensa/actions
          path: .github/actions

      - name: Checkout
        uses: .github/actions/clone-any
        with:
          repository: https://gitlab.com/repotea-workspace/aprinter
          access_token: '${{ secrets.GITLAB_TOKEN }}'

      - name: Generate android key
        uses: .github/actions/gen-android-sign
        with:
          path: android/key.properties
          signingKeyBase64: ${{ secrets.APRINTER_JKS }}
          alias: ${{ secrets.APRINTER_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.APRINTER_STORE_PASSWORD }}
          keyPassword: ${{ secrets.APRINTER_KEY_PASSWORD }}

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'
          channel: 'stable'
      - run: flutter pub get
#      - run: flutter test
      - run: flutter build apk --release
      - run: flutter build appbundle --release
