name: '[paperang] Check'

on:
  push:
    branches:
      - '**'
env:
  FLUTTER_VERSION: '2.x'

jobs:
  build-android:
    name: Build paperang for android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: fewensa/actions
          path: .github/actions

      - name: Checkout
        uses: ./.github/actions/clone-any
        with:
          platform: gitlab
          repository: prtmax/external-paperang
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - name: Generate android sign config file
        uses: ./.github/actions/gen-android-sign
        with:
          path: android/key.properties
          signingKeyBase64: ${{ secrets.PAPERANG_JKS }}
          alias: ${{ secrets.PAPERANG_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.PAPERANG_STORE_PASSWORD }}
          keyPassword: ${{ secrets.PAPERANG_KEY_PASSWORD }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Prepare scripts
        run: |
          git config --global credential.helper store
          echo 'https://${{ secrets.GITLAB_TOKEN }}@gitlab.com' >> ~/.git-credentials

      - name: Try build for android
        run: |
          flutter pub get
          flutter build apk --release

      - name: Check dist for android
        run: ls -la build/app/outputs/apk/release
