name: '[shiprinter] Publish'

on:
  push:
    tags:
      - "v*"


jobs:
  build-desktop:
    name: Build shiprinter for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - windows
          - ubuntu
          # - macos
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: fewensa/actions
          path: .github/actions

      - name: Checkout
        uses: ./.github/actions/clone-any
        with:
          platform: gitlab
          repository: repotea-workspace/shiprinter
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup dependencies
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt install -y clang ninja-build libgtk-3-dev

      - name: Setup platform for windows/macos
        if: matrix.os != 'ubuntu'
        run: flutter config --enable-${{ matrix.os }}-desktop

      - name: Setup platform for ubuntu
        if: matrix.os == 'ubuntu'
        run: flutter config --enable-linux-desktop

      - name: Prepare scripts
        run: |
          git config --global credential.helper store
          echo 'https://${{ secrets.GITLAB_TOKEN }}@gitlab.com' >> ~/.git-credentials
          sh -f scripts/prepare-publish.sh

      - name: Try build for windows/macos
        if: matrix.os != 'ubuntu'
        run: flutter build ${{ matrix.os }} --release

      - name: Try build for ubuntu
        if: matrix.os == 'ubuntu'
        run: flutter build linux --release

      - name: Collect shared for windows
        if: matrix.os == 'windows'
        run: |
          mv build/windows/runner/Release shiprinter
          mkdir -p shared
          7z a -tzip shared/shiprinter-windows-x86_64.zip ./shiprinter

      - name: Collect shared for ubuntu
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt update -y
          sudo apt install -y zip
          mv build/linux/x64/release/bundle shiprinter
          mkdir -p shared
          zip -jr \
            shared/shiprinter-linux-x86_64.zip \
            shiprinter

      - name: Check dist for macos
        if: matrix.os == 'macos'
        run: |
          brew install tree
          brew install coreutils
          tree build

      - name: Upload shared
        uses: actions/upload-artifact@v2
        with:
          name: shared-artifact
          path: shared

  build-android:
    name: Build shiprinter for android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: fewensa/actions
          path: .github/actions

      - name: Checkout
        uses: ./.github/actions/clone-any
        with:
          platform: gitlab
          repository: repotea-workspace/shiprinter
          access_token: '${{ secrets.GITLAB_TOKEN }}'
          ref_file: .github/ref.txt

      - name: Generate android sign config file
        uses: ./.github/actions/gen-android-sign
        with:
          path: android/key.properties
          signingKeyBase64: ${{ secrets.SHIPRINTER_JKS }}
          alias: ${{ secrets.SHIPRINTER_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SHIPRINTER_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SHIPRINTER_KEY_PASSWORD }}

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Prepare scripts
        run: |
          git config --global credential.helper store
          echo 'https://${{ secrets.GITLAB_TOKEN }}@gitlab.com' >> ~/.git-credentials
          sh -f scripts/prepare-publish.sh

      - name: Try build for android
        run: |
          flutter pub get
          flutter build apk --release

      - name: Collect shared for android
        run: |
          mkdir -p shared
          mv build/app/outputs/apk/release/app-release.apk shared/shiprinter.apk

      - name: Upload shared
        uses: actions/upload-artifact@v2
        with:
          name: shared-artifact
          path: shared


  publish-shiprinter:
    name: Publish shiprinter
    runs-on: ubuntu-latest
    needs: [ build-desktop, build-android ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: shared-artifact
          path: shared

      - name: Hash file
        run: |
          (cd shared && sha256sum * | tee sha256sums.txt)

      - name: Publish github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shared/*
          token: ${{ secrets.GITHUB_TOKEN }}

  clean-artifacts:
    name: Clean artifacts
    runs-on: ubuntu-latest
    needs: [ publish-shiprinter ]
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: shared-artifact



